- name: variables
  hosts: local
  connections: local
  vars:
    name: Pavan
    age: 24
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: "hello {{ name }}, age: {{ age }}"