- name: variables
  hosts: local
  connection: local
  vars:
    name: Pavan
    age: 24
  tasks:
  
  - name: task variables
    vars:
      name: nagendra
      age: 24
    ansible.builtin.debug:
      msg: "hello {{ name }} and age is :{{ age }}"
      
  - name: global variables
    ansible.builtin.debug:
      msg: "hello {{ name }} and age is :{{ age }}"   