- name: user define
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: "enter user name:"
    private: false

  - name: password
    prompt: password
    private: true
  
  tasks:
  - name: checking prompts
    ansible.builtin.debug:
      msg: "user name:{{ username }} and password{{ password }}"