- name: shell vs cmd
  hosts: frontend
  tasks:
  - name: redirecting the output
    ansible.builtin.command: "ls -ltr > /tmp/output.txt"
    register: command_register

  - name: status of output for command
    ansible.builtin.debug:
      msg: "{{command_register}}"

  - name: redirecting the output
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"
    register: command_register
    
  - name: status of output for shell
    ansible.builtin.debug:
      msg: "{{command_register}}"