- name: shell vs cmd
  hosts: frontend
  tasks:

  - name: redirecting the output
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"
    register: command_register2

  - name: status of output for shell
    ansible.builtin.debug:
      msg: "{{command_register2}}"