- name: installing nginx
  hosts: dynamic_frontend
  #serial: 2
  become: yes
  tasks:
    - name: installing nginx server
      ansible.builtin.package:
        name: nginx
        state: present
    - name: start nginx server
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes